language: ruby

install:
  - gem install jekyll
  - gem install sass
  - gem install nokogiri
  - gem install rdiscount

script: cd app/ && make

after_success:
    - ./.push_gh_pages.sh

env:
  global:
    SITE_ENV: github_pages

